### ISSUE TITLE
Tenant can be Tenant Id instead of URL?

### ISSUE THREAD

**Issue by jithureddy** [fhellwig/client-credentials#1]
I see the first argument to get access token, we have tenant as URL, but In my application I have tenant id exposed is it ok?

**Comment by fhellwig** [comment]
I'm afraid I don't understand the question. The tenant, as described in [this article](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-protocols-oauth-code), is your AAD tenant identifier.

**Comment by fhellwig** [comment]
Closing due to time elapsed.
